export const CATEGORIES = [
    'Restaurantes',
    'Servicios',
    'Productos',
    'Tiendas',
    'Mascotas',
    'Salud',
    'Belleza',
    'Educación',
    'Entretenimiento',
    'Tecnología'
  ];
  
export const KEYWORDS = {
    // Restaurantes
    // 'comida': 'Restaurantes',
    'restaurante': 'Restaurantes',
    'almuerzo': 'Restaurantes',
    'cena': 'Restaurantes',
    'desayuno': 'Restaurantes',
    // 'pollo': 'Restaurantes',
    // 'asadero': 'Restaurantes',
    // 'pizza': 'Restaurantes',
    // 'hamburguesa': 'Restaurantes',
    // 'antojitos': 'Restaurantes',
    // 'tacos': 'Restaurantes',
    // 'parrilla': 'Restaurantes',
    // 'domicilio': ['Restaurantes', 'Tiendas'],
    // 'delivery': ['Restaurantes', 'Tiendas'],
    // 'menú': 'Restaurantes',
    // 'comida rápida': 'Restaurantes',
    // 'comida gourmet': 'Restaurantes',
    
    // // Servicios
    // 'servicio': 'Servicios',
    // 'peluquería': 'Servicios',
    // 'belleza': 'Servicios',
    // 'gimnasio': 'Servicios',
    // 'veterinaria': 'Servicios',
    // 'mascotas': 'Servicios',
    // 'reparación': 'Servicios',
    // 'mantenimiento': 'Servicios',
    // 'plomería': 'Servicios',
    // 'electricista': 'Servicios',
    // 'limpieza': 'Servicios',
    // 'reparación electrodomésticos': 'Servicios',
    // 'seguridad': 'Servicios',
    // 'transporte': 'Servicios',
    
    // // Productos
    // 'producto': 'Productos',
    // 'artículo': 'Productos',
    // 'mercancía': 'Productos',
    // 'compra': 'Productos',
    // 'venta': 'Productos',
    // 'oferta': 'Productos',
    // 'descuento': 'Productos',
    // 'nuevo producto': 'Productos',
    // 'producto exclusivo': 'Productos',
    // 'producto de calidad': 'Productos',
    // 'producto artesanal': 'Productos',
    
    // // Tiendas
    // 'tienda': 'Tiendas',
    // 'supermercado': 'Tiendas',
    // 'ropa': 'Tiendas',
    // 'mercado': 'Tiendas',
    // 'papelería': 'Tiendas',
    // 'ferretería': 'Tiendas',
    // 'compras': 'Tiendas',
    // 'almacén': 'Tiendas',
    // 'bodega': 'Tiendas',
    // 'moda': 'Tiendas',
    // 'accesorios': 'Tiendas',
    // 'juguetes': 'Tiendas',
    // 'electrónica': 'Tiendas',
    
    // // Salud
    // 'medicina': 'Salud',
    // 'doctor': 'Salud',
    // 'médico': 'Salud',
    // 'farmacia': 'Salud',
    // 'droguería': 'Salud',
    // 'salud': 'Salud',
    // 'consultorio': 'Salud',
    // 'terapia': 'Salud',
    // 'odontología': 'Salud',
    // 'psicología': 'Salud',
    // 'especialista': 'Salud',
    // 'consulta médica': 'Salud',
    // 'tratamiento': 'Salud',
    // 'medicación': 'Salud',
    // 'enfermedad': 'Salud',
    
    // // Educación
    // 'escuela': 'Educación',
    // 'colegio': 'Educación',
    // 'curso': 'Educación',
    // 'clase': 'Educación',
    // 'profesor': 'Educación',
    // 'tutor': 'Educación',
    // 'academia': 'Educación',
    // 'universidad': 'Educación',
    // 'estudio': 'Educación',
    // 'educación': 'Educación',
    // 'tarea': 'Educación',
    // 'examen': 'Educación',
    // 'certificación': 'Educación',
    // 'aprendizaje': 'Educación',
    
    // // Entretenimiento
    // 'entretenimiento': 'Entretenimiento',
    // 'películas': 'Entretenimiento',
    // 'música': 'Entretenimiento',
    // 'videojuegos': 'Entretenimiento',
    // 'ocio': 'Entretenimiento',
    // 'series': 'Entretenimiento',
    // 'teatro': 'Entretenimiento',
    // 'eventos': 'Entretenimiento',
    // 'diversión': 'Entretenimiento',
    // 'deportes': 'Entretenimiento',
    // 'conciertos': 'Entretenimiento',
    
    // // Tecnología
    // 'tecnología': 'Tecnología',
    // 'computador': 'Tecnología',
    // 'celular': 'Tecnología',
    // 'móvil': 'Tecnología',
    // 'smartphone': 'Tecnología',
    // 'internet': 'Tecnología',
    // 'wifi': 'Tecnología',
    // 'software': 'Tecnología',
    // 'hardware': 'Tecnología',
    // 'accesorios': 'Tecnología',
    // 'cargador': 'Tecnología',
    // 'pantalla': 'Tecnología',
    // 'portátil': 'Tecnología',
    // 'tablet': 'Tecnología',
    // 'audífonos': 'Tecnología',
    // 'teclado': 'Tecnología',
    // 'reparación tecnología': 'Tecnología',
    // 'soporte técnico': 'Tecnología',
    // 'innovación': 'Tecnología',
    // 'programación': 'Tecnología',
    // 'código': 'Tecnología'
};

  